version: "3.0"

services:
  server:
    container_name: "nosql2020-battles-server"
    image: "nosql2020-battles-server:latest"
    build: ./backend
    environment:
      - MONGODB_HOST=db
    ports:
      - 3030:3030

  db:
    image: mongo
    restart: always
