version: "3.0"

services:
  backend:
    image: "supersolik/nosql2020-battles-backend:latest"
    ports:
      - 3030:3030
    environment:
      - MONGODB_URI=mongodb://db:27017

  frontend:
    image: "supersolik/nosql2020-battles-frontend:latest"
    ports:
      - 4200:4200

  db:
    image: mongo
    restart: always
